### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by tanmaysharma19** [UBC-MDS/Rmleda#1]
Add a readme with a description about the R package. Include relevant examples and details about the functions.

**Comment by Saule-Atymtayeva** [comment]
EDIT: I added the text in Readme (the `autoimpute_na` part):

The `Rmleda` package is intended to help with EDA for supervised machine learning tasks; there are other existing packages that contain some similar functionality. For example, the packages, namely [`MICE`](https://CRAN.R-project.org/package=mice), [`Amelia`](https://CRAN.R-project.org/package=Amelia), [`missForest`](https://CRAN.R-project.org/package=missForest), [`Hmisc`](https://CRAN.R-project.org/package=Hmisc), and [`mi`](https://CRAN.R-project.org/package=mi), provides users with functions to detect missing values and fill them. Our pymleda package intends to augment the existing functionality of these packages with some additional features.

The `autoimpute_na()` function will additionally detect some common non-standard missing values manually entered by users (e.g., "not available", "n/a", "na", "-") while identifying and imputing missing data. The output of the `autoimpute_na()` function will be a dataframe with imputed values.

**Comment by tanmaysharma19** [comment]
Addressed in  #15.
