### ISSUE TITLE
Update License

### ISSUE THREAD

**Issue by yaz-saleh** [UBC-MDS/Rmleda#40]

**Comment by tanmaysharma19** [comment]
The team discussed the existing choice of MIT license for our project and whether if we wanted to change to a different one. The discussion encompassed taking into consideration the intent, scope, audience, and utility of our package and whether if we wanted to continue with the development and maintenance of the package. 

- The `Rmleda` package was envisaged with an academic intent to learn and practice about package development in R.
- The focus was more on learning the various aspects of package development and incorporating the best practices while doing so.
- While the package brings together functionality from different existing packages and is useful for preliminary EDA for supervised ML tasks, it can still be improved in terms of adding novel functionality or optimizing the methods for carrying out the existing transformations.
- The team is happy to share the package in its current version with the general public.
- The team does not wish to continue forward with active development and maintenance of this package.  

Based on the above points, the team decided to retain the MIT license.

**Comment by yaz-saleh** [comment]
Agreed with the above. While active development of the package is not currently planned, the package can potentially be a useful starting point to further develop into something more complex. On that note, it makes sense to use the MIT license. This would give others freedom to make improved versions regardless if they choose to release them as open or closed source versions.

**Comment by Saule-Atymtayeva** [comment]
Since we are creating the package for educational purposes, I agree with the above team's opinion on using MIT as a base license.

**Comment by rissangs** [comment]
Agreed with the above discussions.
